title: Input binding type safety
position: 60
category: General
preparation: false
estimated_time_in_minutes: 10
always_unlocked: false
git_tag_completed: solution--component-input-binding-type-safety
