title: "[optional] Use router with automatic component input bindings"
position: 60
category: General
preparation: false
estimated_time_in_minutes: 5
always_unlocked: false
git_tag_completed: solution--router-withComponentInputBinding
